// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: decider/v1/decider.proto

package decider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeciderService_ShouldSendMessage_FullMethodName = "/decider.v1.DeciderService/ShouldSendMessage"
)

// DeciderServiceClient is the client API for DeciderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeciderServiceClient interface {
	ShouldSendMessage(ctx context.Context, in *ShouldSendMessageRequest, opts ...grpc.CallOption) (*ShouldSendMessageResponse, error)
}

type deciderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeciderServiceClient(cc grpc.ClientConnInterface) DeciderServiceClient {
	return &deciderServiceClient{cc}
}

func (c *deciderServiceClient) ShouldSendMessage(ctx context.Context, in *ShouldSendMessageRequest, opts ...grpc.CallOption) (*ShouldSendMessageResponse, error) {
	out := new(ShouldSendMessageResponse)
	err := c.cc.Invoke(ctx, DeciderService_ShouldSendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeciderServiceServer is the server API for DeciderService service.
// All implementations must embed UnimplementedDeciderServiceServer
// for forward compatibility
type DeciderServiceServer interface {
	ShouldSendMessage(context.Context, *ShouldSendMessageRequest) (*ShouldSendMessageResponse, error)
	mustEmbedUnimplementedDeciderServiceServer()
}

// UnimplementedDeciderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeciderServiceServer struct {
}

func (UnimplementedDeciderServiceServer) ShouldSendMessage(context.Context, *ShouldSendMessageRequest) (*ShouldSendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShouldSendMessage not implemented")
}
func (UnimplementedDeciderServiceServer) mustEmbedUnimplementedDeciderServiceServer() {}

// UnsafeDeciderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeciderServiceServer will
// result in compilation errors.
type UnsafeDeciderServiceServer interface {
	mustEmbedUnimplementedDeciderServiceServer()
}

func RegisterDeciderServiceServer(s grpc.ServiceRegistrar, srv DeciderServiceServer) {
	s.RegisterService(&DeciderService_ServiceDesc, srv)
}

func _DeciderService_ShouldSendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShouldSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeciderServiceServer).ShouldSendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeciderService_ShouldSendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeciderServiceServer).ShouldSendMessage(ctx, req.(*ShouldSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeciderService_ServiceDesc is the grpc.ServiceDesc for DeciderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeciderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decider.v1.DeciderService",
	HandlerType: (*DeciderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShouldSendMessage",
			Handler:    _DeciderService_ShouldSendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "decider/v1/decider.proto",
}
