// Code generated by MockGen. DO NOT EDIT.
// Source: database.go
//
// Generated by this command:
//
//	mockgen -source=database.go -destination=./mocks/mock_database.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	relayer "github.com/ava-labs/awm-relayer/relayer"
	gomock "go.uber.org/mock/gomock"
)

// MockRelayerDatabase is a mock of RelayerDatabase interface.
type MockRelayerDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockRelayerDatabaseMockRecorder
}

// MockRelayerDatabaseMockRecorder is the mock recorder for MockRelayerDatabase.
type MockRelayerDatabaseMockRecorder struct {
	mock *MockRelayerDatabase
}

// NewMockRelayerDatabase creates a new mock instance.
func NewMockRelayerDatabase(ctrl *gomock.Controller) *MockRelayerDatabase {
	mock := &MockRelayerDatabase{ctrl: ctrl}
	mock.recorder = &MockRelayerDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayerDatabase) EXPECT() *MockRelayerDatabaseMockRecorder {
	return m.recorder
}

// GetLatestProcessedBlockHeight mocks base method.
func (m *MockRelayerDatabase) GetLatestProcessedBlockHeight(relayerID relayer.RelayerID) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestProcessedBlockHeight", relayerID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProcessedBlockHeight indicates an expected call of GetLatestProcessedBlockHeight.
func (mr *MockRelayerDatabaseMockRecorder) GetLatestProcessedBlockHeight(relayerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProcessedBlockHeight", reflect.TypeOf((*MockRelayerDatabase)(nil).GetLatestProcessedBlockHeight), relayerID)
}

// StoreLatestProcessedBlockHeight mocks base method.
func (m *MockRelayerDatabase) StoreLatestProcessedBlockHeight(relayerID relayer.RelayerID, height uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLatestProcessedBlockHeight", relayerID, height)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLatestProcessedBlockHeight indicates an expected call of StoreLatestProcessedBlockHeight.
func (mr *MockRelayerDatabaseMockRecorder) StoreLatestProcessedBlockHeight(relayerID, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLatestProcessedBlockHeight", reflect.TypeOf((*MockRelayerDatabase)(nil).StoreLatestProcessedBlockHeight), relayerID, height)
}
