// Code generated by MockGen. DO NOT EDIT.
// Source: message_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ids "github.com/ava-labs/avalanchego/ids"
	warp "github.com/ava-labs/avalanchego/vms/platformvm/warp"
	vmtypes "github.com/ava-labs/awm-relayer/vms/vmtypes"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageManager is a mock of MessageManager interface.
type MockMessageManager struct {
	ctrl     *gomock.Controller
	recorder *MockMessageManagerMockRecorder
}

// MockMessageManagerMockRecorder is the mock recorder for MockMessageManager.
type MockMessageManagerMockRecorder struct {
	mock *MockMessageManager
}

// NewMockMessageManager creates a new mock instance.
func NewMockMessageManager(ctrl *gomock.Controller) *MockMessageManager {
	mock := &MockMessageManager{ctrl: ctrl}
	mock.recorder = &MockMessageManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageManager) EXPECT() *MockMessageManagerMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessageManager) SendMessage(signedMessage *warp.Message, parsedVMPayload []byte, destinationBlockchainID ids.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", signedMessage, parsedVMPayload, destinationBlockchainID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageManagerMockRecorder) SendMessage(signedMessage, parsedVMPayload, destinationBlockchainID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageManager)(nil).SendMessage), signedMessage, parsedVMPayload, destinationBlockchainID)
}

// ShouldSendMessage mocks base method.
func (m *MockMessageManager) ShouldSendMessage(warpMessageInfo *vmtypes.WarpMessageInfo, destinationBlockchainID ids.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldSendMessage", warpMessageInfo, destinationBlockchainID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldSendMessage indicates an expected call of ShouldSendMessage.
func (mr *MockMessageManagerMockRecorder) ShouldSendMessage(warpMessageInfo, destinationBlockchainID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldSendMessage", reflect.TypeOf((*MockMessageManager)(nil).ShouldSendMessage), warpMessageInfo, destinationBlockchainID)
}
