# ref. https://goreleaser.com/customization/build/
project_name: signature-aggregator
monorepo:
  tag_prefix: signature-aggregator/
builds:
  - id: signature-aggregator
    main: ./signature-aggregator/main/main.go
    binary: signature-aggregator
    flags:
      - -v
    # windows is ignored by default, as the `goos` field by default only
    # contains linux and darwin
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__ # Set the CGO flags to use the portable version of BLST
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
    ignore:
      - goos: darwin
        goarch: amd64
dockers:
  - image_templates:
    - 'avaplatform/signature-aggregator:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    dockerfile: "signature-aggregator/Dockerfile"
  - image_templates:
    - 'avaplatform/signature-aggregator:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    dockerfile: "signature-aggregator/Dockerfile"
    goarch: arm64
docker_manifests:
  - name_template: 'avaplatform/signature-aggregator:{{ .Tag }}'
    image_templates:
    - 'avaplatform/signature-aggregator:{{ .Tag }}-amd64'
    - 'avaplatform/signature-aggregator:{{ .Tag }}-arm64'
  - name_template: 'avaplatform/signature-aggregator:latest'
    image_templates:
    - 'avaplatform/signature-aggregator:{{ .Tag }}-amd64'
    - 'avaplatform/signature-aggregator:{{ .Tag }}-arm64'
    # If tag is an rc, do not push the latest tag
    skip_push: auto
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: ava-labs
    name: icm-relayer
  # If tag indicates rc, will mark it as prerelease
  prerelease: auto
