# ref. https://goreleaser.com/customization/build/
project_name: awm-relayer
monorepo:
  tag_prefix: awm-relayer/
builds:
  - id: awm-relayer
    main: ./relayer/main/main.go
    binary: awm-relayer
    flags:
      - -v
    # windows is ignored by default, as the `goos` field by default only
    # contains linux and darwin
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__ # Set the CGO flags to use the portable version of BLST
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
    ignore:
      - goos: darwin
        goarch: amd64
dockers:
  - image_templates:
    - 'avaplatform/awm-relayer:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    dockerfile: "relayer/Dockerfile"
  - image_templates:
    - 'avaplatform/awm-relayer:{{ .Tag }}-arm64'
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64"
    dockerfile: "relayer/Dockerfile"
    goarch: arm64
docker_manifests:
  - name_template: 'avaplatform/awm-relayer:{{ .Tag }}'
    image_templates:
    - 'avaplatform/awm-relayer:{{ .Tag }}-amd64'
    - 'avaplatform/awm-relayer:{{ .Tag }}-arm64'
  - name_template: 'avaplatform/awm-relayer:latest'
    image_templates:
    - 'avaplatform/awm-relayer:{{ .Tag }}-amd64'
    - 'avaplatform/awm-relayer:{{ .Tag }}-arm64'
    # If tag is an rc, do not push the latest tag
    skip_push: auto
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: ava-labs
    name: awm-relayer
  # If tag indicates rc, will mark it as prerelease
  prerelease: auto
