// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: decider/decider.proto

package decider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Decider_ShouldSendMessage_FullMethodName = "/decider.Decider/ShouldSendMessage"
)

// DeciderClient is the client API for Decider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeciderClient interface {
	ShouldSendMessage(ctx context.Context, in *UnsignedWarpMessage, opts ...grpc.CallOption) (*ShouldSendMessageResponse, error)
}

type deciderClient struct {
	cc grpc.ClientConnInterface
}

func NewDeciderClient(cc grpc.ClientConnInterface) DeciderClient {
	return &deciderClient{cc}
}

func (c *deciderClient) ShouldSendMessage(ctx context.Context, in *UnsignedWarpMessage, opts ...grpc.CallOption) (*ShouldSendMessageResponse, error) {
	out := new(ShouldSendMessageResponse)
	err := c.cc.Invoke(ctx, Decider_ShouldSendMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeciderServer is the server API for Decider service.
// All implementations must embed UnimplementedDeciderServer
// for forward compatibility
type DeciderServer interface {
	ShouldSendMessage(context.Context, *UnsignedWarpMessage) (*ShouldSendMessageResponse, error)
	mustEmbedUnimplementedDeciderServer()
}

// UnimplementedDeciderServer must be embedded to have forward compatible implementations.
type UnimplementedDeciderServer struct {
}

func (UnimplementedDeciderServer) ShouldSendMessage(context.Context, *UnsignedWarpMessage) (*ShouldSendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShouldSendMessage not implemented")
}
func (UnimplementedDeciderServer) mustEmbedUnimplementedDeciderServer() {}

// UnsafeDeciderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeciderServer will
// result in compilation errors.
type UnsafeDeciderServer interface {
	mustEmbedUnimplementedDeciderServer()
}

func RegisterDeciderServer(s grpc.ServiceRegistrar, srv DeciderServer) {
	s.RegisterService(&Decider_ServiceDesc, srv)
}

func _Decider_ShouldSendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsignedWarpMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeciderServer).ShouldSendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Decider_ShouldSendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeciderServer).ShouldSendMessage(ctx, req.(*UnsignedWarpMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Decider_ServiceDesc is the grpc.ServiceDesc for Decider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Decider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decider.Decider",
	HandlerType: (*DeciderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShouldSendMessage",
			Handler:    _Decider_ShouldSendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "decider/decider.proto",
}
