// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: mock_decider/mock_decider.proto

package mock_decider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MockDecider_SetShouldSendMessageResponse_FullMethodName = "/mock_decider.MockDecider/SetShouldSendMessageResponse"
)

// MockDeciderClient is the client API for MockDecider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockDeciderClient interface {
	SetShouldSendMessageResponse(ctx context.Context, in *SetShouldSendMessageResponseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mockDeciderClient struct {
	cc grpc.ClientConnInterface
}

func NewMockDeciderClient(cc grpc.ClientConnInterface) MockDeciderClient {
	return &mockDeciderClient{cc}
}

func (c *mockDeciderClient) SetShouldSendMessageResponse(ctx context.Context, in *SetShouldSendMessageResponseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MockDecider_SetShouldSendMessageResponse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockDeciderServer is the server API for MockDecider service.
// All implementations must embed UnimplementedMockDeciderServer
// for forward compatibility
type MockDeciderServer interface {
	SetShouldSendMessageResponse(context.Context, *SetShouldSendMessageResponseRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMockDeciderServer()
}

// UnimplementedMockDeciderServer must be embedded to have forward compatible implementations.
type UnimplementedMockDeciderServer struct {
}

func (UnimplementedMockDeciderServer) SetShouldSendMessageResponse(context.Context, *SetShouldSendMessageResponseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetShouldSendMessageResponse not implemented")
}
func (UnimplementedMockDeciderServer) mustEmbedUnimplementedMockDeciderServer() {}

// UnsafeMockDeciderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockDeciderServer will
// result in compilation errors.
type UnsafeMockDeciderServer interface {
	mustEmbedUnimplementedMockDeciderServer()
}

func RegisterMockDeciderServer(s grpc.ServiceRegistrar, srv MockDeciderServer) {
	s.RegisterService(&MockDecider_ServiceDesc, srv)
}

func _MockDecider_SetShouldSendMessageResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetShouldSendMessageResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDeciderServer).SetShouldSendMessageResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDecider_SetShouldSendMessageResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDeciderServer).SetShouldSendMessageResponse(ctx, req.(*SetShouldSendMessageResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockDecider_ServiceDesc is the grpc.ServiceDesc for MockDecider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockDecider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mock_decider.MockDecider",
	HandlerType: (*MockDeciderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetShouldSendMessageResponse",
			Handler:    _MockDecider_SetShouldSendMessageResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mock_decider/mock_decider.proto",
}
