# Copyright (C) 2024, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: Release signature-aggregator

on:
  push:
    tags:
      - "signature-aggregator/*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # The GO_VERSION must be set explicitly to be used in the Dockerfile.
      - name: Set Go version
        run: |
          source ./scripts/versions.sh
          echo GO_VERSION=$GO_VERSION >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Set up arm64 cross compiler
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-aarch64-linux-gnu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout osxcross
        uses: actions/checkout@v4
        with:
          repository: tpoechtrager/osxcross
          path: osxcross

      - name: Build osxcross
        run: |
          sudo apt-get -y install clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio libbz2-dev
          cd osxcross
          wget https://github.com/joseluisq/macosx-sdks/releases/download/12.3/$MACOS_SDK_FNAME -O tarballs/$MACOS_SDK_FNAME
          echo $MACOS_SDK_CHECKSUM tarballs/$MACOS_SDK_FNAME | sha256sum -c -
          UNATTENDED=1 ./build.sh
          echo $PWD/target/bin >> $GITHUB_PATH
        env:
          MACOS_SDK_FNAME: MacOSX12.3.sdk.tar.xz
          MACOS_SDK_CHECKSUM: 3abd261ceb483c44295a6623fdffe5d44fc4ac2c872526576ec5ab5ad0f6e26c

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean --config signature-aggregator/.goreleaser.yml
        env:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
